# Generated by Django 5.2.17 on 2026-08-24 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0001_initial'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='couples.couple')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_hero_images', to='mediafiles.mediaasset')),
            ],
            options={
                'db_table': 'couple_hero_images',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['couple', 'sort_order'], name='couple_hero_couple__28c604_idx'), models.Index(fields=['media'], name='couple_hero_media_i_4aefce_idx')],
                'constraints': [models.UniqueConstraint(fields=('couple', 'media'), name='unique_hero_media_per_couple')],
            },
        ),
    ]
