# Generated by Django 5.2.17 on 2026-08-23 00:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_couples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couples',
            },
        ),
        migrations.CreateModel(
            name='CoupleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.TextField(choices=[('her', 'Her'), ('him', 'Him')])),
                ('name', models.TextField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('accent_color', models.CharField(default='#ed93b1', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('status_note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(80)])),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_members', to='mediafiles.mediaasset')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='couples.couple')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couple_members',
            },
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['owner', '-created_at'], name='couples_owner_i_e20676_idx'),
        ),
        migrations.AddIndex(
            model_name='couplemember',
            index=models.Index(fields=['couple', 'role'], name='couple_memb_couple__05299a_idx'),
        ),
        migrations.AddIndex(
            model_name='couplemember',
            index=models.Index(fields=['user'], name='couple_memb_user_id_077dc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='couplemember',
            constraint=models.UniqueConstraint(fields=('couple', 'role'), name='unique_member_role_per_couple'),
        ),
    ]
