# Generated by Django 5.2.17 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["couple", "latitude", "longitude"],
                name="memories_couple__0c2ae6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memory",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__isnull", True))
                | (models.Q(("latitude__gte", -90)) & models.Q(("latitude__lte", 90))),
                name="memory_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="memory",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__isnull", True))
                | (models.Q(("longitude__gte", -180)) & models.Q(("longitude__lte", 180))),
                name="memory_longitude_range",
            ),
        ),
    ]
