# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_memory_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorymedia",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="memorymedia",
            name="location_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="memorymedia",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="memorymedia",
            name="place",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="memory_media", to="memories.place"),
        ),
        migrations.AddField(
            model_name="memorymedia",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="memorymedia",
            index=models.Index(fields=["place"], name="memory_medi_place_i_34b626_idx"),
        ),
        migrations.AddConstraint(
            model_name="memorymedia",
            constraint=models.CheckConstraint(condition=models.Q(("latitude__isnull", True)) | (models.Q(("latitude__gte", -90)) & models.Q(("latitude__lte", 90))), name="memory_media_latitude_range"),
        ),
        migrations.AddConstraint(
            model_name="memorymedia",
            constraint=models.CheckConstraint(condition=models.Q(("longitude__isnull", True)) | (models.Q(("longitude__gte", -180)) & models.Q(("longitude__lte", 180))), name="memory_media_longitude_range"),
        ),
    ]
