# Generated by Django 5.2.17 on 2026-08-23 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.TextField(choices=[('trip', 'Trip'), ('coffee', 'Coffee'), ('home', 'Home'), ('date', 'Date'), ('other', 'Other')], default='other')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='couples.couple')),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_places', to='mediafiles.mediaasset')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(160)])),
                ('caption', models.TextField(blank=True)),
                ('location_name', models.TextField(blank=True)),
                ('mood_emoji', models.CharField(default='❤️', max_length=16)),
                ('category', models.TextField(choices=[('travel', 'Travel'), ('food', 'Food'), ('movie', 'Movie'), ('coffee', 'Coffee'), ('gift', 'Gift'), ('other', 'Other')], default='other')),
                ('happened_at', models.DateTimeField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='couples.couple')),
                ('primary_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_memories', to='mediafiles.mediaasset')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='memories.place')),
            ],
            options={
                'db_table': 'memories',
                'ordering': ['-happened_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('caption', models.TextField(blank=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_links', to='mediafiles.mediaasset')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='memories.memory')),
            ],
            options={
                'db_table': 'memory_media',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['memory', 'sort_order'], name='memory_medi_memory__c900db_idx'), models.Index(fields=['media'], name='memory_medi_media_i_6874e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('memory', 'media'), name='unique_media_per_memory')],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['couple', 'category'], name='places_couple__90fad5_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['couple', 'name'], name='places_couple__421e62_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('couple', 'name'), name='unique_place_name_per_couple'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='place_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='place_longitude_range'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['couple', '-happened_at'], name='memories_couple__5ce66e_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['couple', 'category'], name='memories_couple__aff506_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['couple', 'is_favorite'], name='memories_couple__131348_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['place'], name='memories_place_i_47cea4_idx'),
        ),
    ]
