# Generated by Django 5.2.17 on 2026-08-23 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.TextField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='image')),
                ('original_filename', models.TextField(blank=True)),
                ('mime_type', models.TextField(blank=True)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('cloudinary_public_id', models.TextField(blank=True)),
                ('secure_url', models.URLField(blank=True, max_length=1200)),
                ('optimized_url', models.URLField(blank=True, max_length=1200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_assets',
                'indexes': [models.Index(fields=['owner', '-created_at'], name='media_asset_owner_i_71189f_idx'), models.Index(fields=['kind'], name='media_asset_kind_66cf31_idx')],
            },
        ),
    ]
